server:
  port: 8080
spring:
  datasource:
    druid:
      url: 'jdbc:mysql://localhost:3306/tx?autoReconnect=true&serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=UTF-8'
      username: "root"
      password: "root"
      initial-size: 10
      max-wait: 1000
      max-active: 50
      min-idle: 10
      use-unfair-lock: true
      test-while-idle: true
      validation-query: SELECT 1 FROM DUAL
      time-between-eviction-runs-millis: 60000
      keep-alive: true
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 1800000

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    mapUnderscoreToCamelCase: true
  mapper-locations: classpath*:/mappers/**/*.xml

#通用mapper配置
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: false
  identity: MYSQL

#分页插件配置
pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  page-size-zero: count=countSql%