server:
  port: 6070

eureka:
  instance:
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9100/eureka/


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/inst01?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Aa123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  data:
#    mongodb:
#      uri: mongodb://10.37.147.250:27017/bytetcc
#  cloud:
#    zookeeper:
#      connectString: 127.0.0.1:2181
